spring:
  application:
    name: RAML Sample API
  profiles:
    active: null
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  mvc:
    favicon:
      enabled: false
server:
  port: 8080
logging:
  level:
    com.company.sample: DEBUG